export const solutionPages = {
  en: {
    'zero-trust-security': {
      title: 'Zero Trust Security with Defender & Sentinel',
      eyebrow: 'Security & Compliance',
      lead: 'End-to-end protection across endpoints, identities and cloud workloads with XDR, SIEM and clear incident response.',
      subline: 'Built on Microsoft Defender XDR, Sentinel, Entra ID and practical governance.',
      icon: 'security',
      buyer: ['CIOs and IT managers modernizing security operations', 'Regulated mid-market teams that need evidence and auditability', 'Organizations with distributed endpoints, identities and cloud workloads'],
      deliver: ['Defender XDR coverage across endpoint, identity and cloud signals', 'Sentinel SIEM/SOAR use cases, alert routing and incident workflow', 'Conditional Access and MFA baseline aligned to real business risk', 'Threat reporting, escalation paths and monthly improvement backlog'],
      standards: ['Microsoft Defender XDR', 'Microsoft Sentinel', 'Entra ID', 'Zero Trust', 'GDPR-aware governance'],
      caseTitle: 'Anonymized outcome',
      caseBody: 'A distributed business consolidated endpoint and identity signals into a central response model, reducing blind spots and making monthly risk conversations evidence-based.',
      caseMetrics: ['central alerts', 'defined escalation', 'measurable risk']
    },
    'entra-id-sso': {
      title: 'Entra ID & SSO Consolidation',
      eyebrow: 'Identity & Endpoint',
      lead: 'Bring SaaS and line-of-business applications under one identity with conditional access, MFA and auditability.',
      subline: 'One identity plane, controlled access, clean offboarding and a full audit trail.',
      icon: 'target',
      buyer: ['IT leaders managing SaaS sprawl', 'Businesses that need stronger access control without blocking users', 'Teams preparing for M365, Intune or security governance projects'],
      deliver: ['Application inventory and identity ownership model', 'SSO integration for SaaS and business-critical tools', 'Conditional Access and MFA policy design', 'Joiner/mover/leaver access process and reporting'],
      standards: ['Microsoft Entra ID', 'SSO / SAML / OIDC', 'Conditional Access', 'MFA', 'Audit logs'],
      caseTitle: 'Anonymized outcome',
      caseBody: 'A mid-market organization reduced identity fragmentation by consolidating core SaaS applications under Entra ID with consistent MFA and access rules.',
      caseMetrics: ['single identity', 'controlled access', 'clean offboarding']
    },
    'backup-dr-veeam': {
      title: 'Backup & DR with Veeam',
      eyebrow: 'Business Continuity',
      lead: 'Design and operate a 3-2-1 backup strategy with immutable repositories and tested recovery.',
      subline: 'Backup is not a checkbox. Recovery must be designed, documented and rehearsed.',
      icon: 'backup',
      buyer: ['IT managers responsible for business continuity', 'Organizations running VMware, Hyper-V, M365 or physical workloads', 'Leadership teams that need realistic RPO/RTO planning'],
      deliver: ['Backup and recovery assessment with risk gaps', '3-2-1 architecture with immutable repository options', 'Recovery runbooks for priority workloads', 'Scheduled restore testing and executive reporting'],
      standards: ['Veeam', '3-2-1 backup', 'Immutable repositories', 'VMware / Hyper-V', 'Microsoft 365 backup'],
      caseTitle: 'Anonymized outcome',
      caseBody: 'A hybrid infrastructure environment gained a clearer recovery model by separating backup policy, restore testing and incident ownership.',
      caseMetrics: ['tested restores', 'clear RPO/RTO', 'runbooks']
    },
    'cloud-migration': {
      title: 'Cloud Migration Services',
      eyebrow: 'Migration & Modernization',
      lead: 'Phased Google Workspace to Microsoft 365 migration for mail, files and identity with minimal downtime.',
      subline: 'A migration is successful when users keep working and governance improves after cutover.',
      icon: 'cloud',
      buyer: ['Organizations moving from Google Workspace to Microsoft 365', 'Teams that need mailbox, Drive and identity migration with low disruption', 'IT leaders looking for clear runbooks and user communication'],
      deliver: ['Discovery, dependency mapping and migration plan', 'Mailbox, Drive and identity migration runbooks', 'Pilot migration, cutover planning and rollback thinking', 'User communication, support window and post-migration stabilization'],
      standards: ['Microsoft 365', 'Google Workspace', 'ShareGate', 'Migration runbooks', 'User adoption'],
      caseTitle: 'Anonymized outcome',
      caseBody: 'A distributed team migrated communication and files in phases, keeping downtime low while improving identity and device governance.',
      caseMetrics: ['phased cutover', 'minimal downtime', 'user comms']
    },
    'microsoft-azure': {
      title: 'Microsoft Azure',
      eyebrow: 'Cloud Infrastructure',
      lead: 'Design, build and operate Azure infrastructure with secure networking, governance and cost control.',
      subline: 'Cloud resources are only useful when they are resilient, monitored and supportable.',
      icon: 'cloud',
      buyer: ['IT leaders planning cloud infrastructure', 'Teams replacing aging on-prem platforms', 'Businesses that need secure, scalable hosting'],
      deliver: ['Azure landing zone and subscription structure', 'Secure networking, monitoring and identity integration', 'Cost governance, tagging and operational reporting', 'Runbooks for support, change and incident handling'],
      standards: ['Microsoft Azure', 'Landing zones', 'Azure Monitor', 'Entra ID', 'FinOps'],
      caseTitle: 'Anonymized outcome',
      caseBody: 'A business infrastructure footprint was moved into a clearer Azure operating model with controlled access, better monitoring and documented ownership.',
      caseMetrics: ['secure cloud', 'cost control', 'runbooks']
    },
    'microsoft-365': {
      title: 'Microsoft 365',
      eyebrow: 'Modern Workplace',
      lead: 'Deploy Microsoft 365 collaboration with security, device alignment and practical governance.',
      subline: 'Teams, SharePoint and Exchange work best when identity, devices and data rules are designed together.',
      icon: 'platform',
      buyer: ['Organizations standardizing collaboration', 'Teams improving mail, files and device governance', 'IT managers reducing workplace support friction'],
      deliver: ['Teams, SharePoint and Exchange configuration', 'M365 security and governance baseline', 'Entra, Intune and Defender alignment', 'User adoption, support model and admin handover'],
      standards: ['Microsoft 365', 'Teams', 'SharePoint', 'Exchange', 'Intune'],
      caseTitle: 'Anonymized outcome',
      caseBody: 'A workplace environment became easier to operate after collaboration, identity and endpoint controls were aligned under one governance model.',
      caseMetrics: ['secure collaboration', 'device governance', 'handover']
    },
    'vmware-proxmox-virtualization': {
      title: 'VMware & Proxmox Virtualization',
      eyebrow: 'Virtualization',
      lead: 'Consolidate, optimize and operate on-prem virtualization with VMware or Proxmox depending on business and licensing needs.',
      subline: 'The right virtualization platform balances availability, cost, lifecycle and supportability.',
      icon: 'virtualization',
      buyer: ['Organizations modernizing on-prem compute', 'Teams reviewing VMware cost and lifecycle options', 'Businesses that need reliable private infrastructure'],
      deliver: ['Current-state assessment and capacity planning', 'VMware or Proxmox target architecture', 'Migration plan for workloads and storage', 'Backup, monitoring and operational handover'],
      standards: ['VMware', 'Proxmox', 'KVM', 'Storage', 'High availability'],
      caseTitle: 'Anonymized outcome',
      caseBody: 'A private infrastructure environment gained clearer capacity planning, backup alignment and platform ownership after virtualization redesign.',
      caseMetrics: ['right-sized hosts', 'HA planning', 'lower risk']
    },
    'azure-hybrid-cloud': {
      title: 'Azure Hybrid Cloud Integration',
      eyebrow: 'Hybrid Cloud',
      lead: 'Extend on-prem VMware or Proxmox environments into Azure for scalability, disaster recovery and secure hybrid operations.',
      subline: 'Hybrid works when connectivity, identity, monitoring and recovery are designed as one system.',
      icon: 'infrastructure',
      buyer: ['Teams that cannot move everything to cloud at once', 'Organizations needing DR or burst capacity in Azure', 'IT leaders operating both cloud and on-prem platforms'],
      deliver: ['Hybrid connectivity and identity design', 'Azure extension for selected workloads and DR scenarios', 'Unified monitoring and backup alignment', 'Operational model for cloud/on-prem ownership'],
      standards: ['Azure', 'VPN / ExpressRoute', 'Hybrid identity', 'Azure Monitor', 'DR planning'],
      caseTitle: 'Anonymized outcome',
      caseBody: 'A hybrid environment reduced operational ambiguity by defining what runs on-prem, what extends to Azure and how both sides are monitored and recovered.',
      caseMetrics: ['hybrid DR', 'secure connectivity', 'unified monitoring']
    },
    'web-b2b-b2c': {
      title: 'Web-Based B2B & B2C Solutions',
      eyebrow: 'Business Platforms',
      lead: 'Custom web platforms integrated with ERP and business systems to match exact operational processes.',
      subline: 'Useful software reflects the real process — not the other way around.',
      icon: 'web',
      buyer: ['Businesses with ordering or workflow complexity', 'Teams that need ERP-integrated customer or partner portals', 'Operations leaders replacing manual data transfer'],
      deliver: ['Process mapping and platform scope', 'ERP/API integration architecture', 'Secure modular web application delivery', 'Operational handover and support model'],
      standards: ['React / web apps', 'ERP integration', 'APIs', 'Security boundaries', 'Operational handover'],
      caseTitle: 'Anonymized outcome',
      caseBody: 'A workflow-heavy business reduced manual coordination by moving order and data flows into an integrated web platform with clearer ownership.',
      caseMetrics: ['ERP integration', 'less manual work', 'clear ownership']
    },
    'easy-order-platform': {
      title: 'Easy Order Web Platform',
      eyebrow: 'Order Management',
      lead: 'Integrated order-process platform connecting customers, manufacturers, warehouses and distributors.',
      subline: 'Order workflows become faster when data transfer is automatic and visible to the right parties.',
      icon: 'tools',
      buyer: ['Organizations coordinating orders across multiple parties', 'Teams replacing spreadsheet/email order workflows', 'Businesses that need status visibility and fewer manual handoffs'],
      deliver: ['Order-flow mapping and role model', 'Customer, manufacturer, warehouse and distributor data paths', 'Automation rules and integration points', 'Support, reporting and operational handover'],
      standards: ['Order workflows', 'Data automation', 'Role-based access', 'ERP integration', 'Reporting'],
      caseTitle: 'Anonymized outcome',
      caseBody: 'A multi-party order process became easier to track and operate after replacing manual handoffs with an integrated workflow platform.',
      caseMetrics: ['automated flow', 'role visibility', 'fewer handoffs']
    },
    'gxp-clinical-research-it': {
      title: 'GxP & Clinical Research IT',
      eyebrow: 'Life Sciences IT',
      lead: 'Validated, audit-ready IT environments for CRO, clinical research and regulated life-sciences teams.',
      subline: 'Practical CSV and GAMP 5 aligned delivery for systems that need evidence, traceability and controlled change.',
      icon: 'security',
      buyer: ['CRO and clinical research teams running regulated workflows', 'Life-sciences organizations preparing for audits or inspections', 'IT leaders who need validation evidence without heavyweight consulting overhead'],
      deliver: ['GxP-relevant system inventory, ownership and risk classification', 'CSV / GAMP 5 aligned implementation and change-control evidence', 'Identity, backup, audit trail and access-review operating model', 'Vendor governance, SOP alignment and recovery evidence for regulated systems'],
      standards: ['GxP-aware IT', 'CSV', 'GAMP 5 aligned', 'Audit trails', 'Controlled change'],
      caseTitle: 'Anonymized outcome',
      caseBody: 'A regulated research team improved audit readiness by mapping system ownership, access evidence, backup proof and change-control records into one operating model.',
      caseMetrics: ['audit evidence', 'controlled change', 'clear ownership']
    }
  },
  bg: {
    'zero-trust-security': {
      title: 'Zero Trust сигурност с Defender и Sentinel',
      eyebrow: 'Сигурност и съответствие',
      lead: 'Цялостна защита на устройства, идентичности и cloud workloads чрез XDR, SIEM и ясен incident response.',
      subline: 'Изградено върху Microsoft Defender XDR, Sentinel, Entra ID и практичен governance.',
      icon: 'security',
      buyer: ['CIO и IT мениджъри, които модернизират security operations', 'Регулирани mid-market екипи с нужда от доказателства и auditability', 'Организации с разпределени устройства, идентичности и cloud workloads'],
      deliver: ['Defender XDR покритие за endpoint, identity и cloud сигнали', 'Sentinel SIEM/SOAR use cases, alert routing и incident workflow', 'Conditional Access и MFA baseline според реалния бизнес риск', 'Threat reporting, escalation paths и месечен improvement backlog'],
      standards: ['Microsoft Defender XDR', 'Microsoft Sentinel', 'Entra ID', 'Zero Trust', 'GDPR-aware governance'],
      caseTitle: 'Анонимизиран резултат',
      caseBody: 'Разпределен бизнес консолидира endpoint и identity сигналите в централен response model, с по-малко blind spots и evidence-based risk разговори.',
      caseMetrics: ['central alerts', 'defined escalation', 'measurable risk']
    },
    'entra-id-sso': {
      title: 'Entra ID и SSO консолидация',
      eyebrow: 'Идентичност и endpoint',
      lead: 'Обединяване на SaaS и бизнес приложения под една идентичност с Conditional Access, MFA и audit trail.',
      subline: 'Един identity plane, контролиран достъп, чист offboarding и пълна проследимост.',
      icon: 'target',
      buyer: ['IT лидери, управляващи SaaS sprawl', 'Бизнеси с нужда от по-силен контрол без блокиране на потребителите', 'Екипи, подготвящи M365, Intune или security governance проекти'],
      deliver: ['Инвентаризация на приложения и identity ownership model', 'SSO интеграция за SaaS и критични бизнес инструменти', 'Conditional Access и MFA policy design', 'Joiner/mover/leaver процес и отчетност'],
      standards: ['Microsoft Entra ID', 'SSO / SAML / OIDC', 'Conditional Access', 'MFA', 'Audit logs'],
      caseTitle: 'Анонимизиран резултат',
      caseBody: 'Mid-market организация намали identity fragmentation чрез консолидация на основните SaaS приложения под Entra ID с последователни MFA и access rules.',
      caseMetrics: ['single identity', 'controlled access', 'clean offboarding']
    },
    'backup-dr-veeam': {
      title: 'Backup и DR с Veeam',
      eyebrow: 'Business Continuity',
      lead: 'Дизайн и управление на 3-2-1 backup стратегия с immutable repositories и тествано възстановяване.',
      subline: 'Backup не е checkbox. Recovery трябва да е проектирано, документирано и репетирано.',
      icon: 'backup',
      buyer: ['IT мениджъри, отговорни за business continuity', 'Организации с VMware, Hyper-V, M365 или physical workloads', 'Management екипи с нужда от реалистично RPO/RTO планиране'],
      deliver: ['Backup и recovery assessment с risk gaps', '3-2-1 архитектура с immutable repository опции', 'Recovery runbooks за priority workloads', 'Планирани restore тестове и executive reporting'],
      standards: ['Veeam', '3-2-1 backup', 'Immutable repositories', 'VMware / Hyper-V', 'Microsoft 365 backup'],
      caseTitle: 'Анонимизиран резултат',
      caseBody: 'Hybrid infrastructure среда получи по-ясен recovery model чрез разделяне на backup policy, restore testing и incident ownership.',
      caseMetrics: ['tested restores', 'clear RPO/RTO', 'runbooks']
    },
    'cloud-migration': {
      title: 'Cloud migration услуги',
      eyebrow: 'Миграция и модернизация',
      lead: 'Поетапна миграция от Google Workspace към Microsoft 365 за поща, файлове и идентичност с минимален downtime.',
      subline: 'Миграцията е успешна, когато потребителите продължат да работят и governance се подобри след cutover.',
      icon: 'cloud',
      buyer: ['Организации, преминаващи от Google Workspace към Microsoft 365', 'Екипи с нужда от mailbox, Drive и identity migration с ниско прекъсване', 'IT лидери, които търсят ясни runbooks и user communication'],
      deliver: ['Discovery, dependency mapping и migration plan', 'Mailbox, Drive и identity migration runbooks', 'Pilot migration, cutover planning и rollback thinking', 'User communication, support window и post-migration stabilization'],
      standards: ['Microsoft 365', 'Google Workspace', 'ShareGate', 'Migration runbooks', 'User adoption'],
      caseTitle: 'Анонимизиран резултат',
      caseBody: 'Разпределен екип мигрира комуникация и файлове поетапно, с нисък downtime и подобрен identity/device governance.',
      caseMetrics: ['phased cutover', 'minimal downtime', 'user comms']
    },
    'microsoft-azure': {
      title: 'Microsoft Azure',
      eyebrow: 'Cloud Infrastructure',
      lead: 'Дизайн, изграждане и управление на Azure infrastructure със сигурна мрежа, governance и cost control.',
      subline: 'Cloud resources са полезни, когато са resilient, monitored и supportable.',
      icon: 'cloud',
      buyer: ['IT лидери, планиращи cloud infrastructure', 'Екипи, заменящи остарели on-prem platforms', 'Бизнеси с нужда от secure, scalable hosting'],
      deliver: ['Azure landing zone и subscription structure', 'Secure networking, monitoring и identity integration', 'Cost governance, tagging и operational reporting', 'Runbooks за support, change и incident handling'],
      standards: ['Microsoft Azure', 'Landing zones', 'Azure Monitor', 'Entra ID', 'FinOps'],
      caseTitle: 'Анонимизиран резултат',
      caseBody: 'Business infrastructure footprint беше преместен в по-ясен Azure operating model с controlled access, по-добър monitoring и documented ownership.',
      caseMetrics: ['secure cloud', 'cost control', 'runbooks']
    },
    'microsoft-365': {
      title: 'Microsoft 365',
      eyebrow: 'Modern Workplace',
      lead: 'Microsoft 365 collaboration със security, device alignment и практичен governance.',
      subline: 'Teams, SharePoint и Exchange работят най-добре, когато identity, devices и data rules са проектирани заедно.',
      icon: 'platform',
      buyer: ['Организации, стандартизиращи collaboration', 'Екипи, подобряващи mail, files и device governance', 'IT мениджъри, намаляващи workplace support friction'],
      deliver: ['Teams, SharePoint и Exchange configuration', 'M365 security и governance baseline', 'Entra, Intune и Defender alignment', 'User adoption, support model и admin handover'],
      standards: ['Microsoft 365', 'Teams', 'SharePoint', 'Exchange', 'Intune'],
      caseTitle: 'Анонимизиран резултат',
      caseBody: 'Workplace среда стана по-лесна за управление след alignment на collaboration, identity и endpoint controls в един governance model.',
      caseMetrics: ['secure collaboration', 'device governance', 'handover']
    },
    'vmware-proxmox-virtualization': {
      title: 'VMware и Proxmox виртуализация',
      eyebrow: 'Virtualization',
      lead: 'Консолидация, оптимизация и управление на on-prem virtualization с VMware или Proxmox според business и licensing нужди.',
      subline: 'Правилната virtualization platform балансира availability, cost, lifecycle и supportability.',
      icon: 'virtualization',
      buyer: ['Организации, модернизиращи on-prem compute', 'Екипи, преглеждащи VMware cost и lifecycle options', 'Бизнеси с нужда от reliable private infrastructure'],
      deliver: ['Current-state assessment и capacity planning', 'VMware или Proxmox target architecture', 'Migration plan за workloads и storage', 'Backup, monitoring и operational handover'],
      standards: ['VMware', 'Proxmox', 'KVM', 'Storage', 'High availability'],
      caseTitle: 'Анонимизиран резултат',
      caseBody: 'Private infrastructure среда получи по-ясно capacity planning, backup alignment и platform ownership след virtualization redesign.',
      caseMetrics: ['right-sized hosts', 'HA planning', 'lower risk']
    },
    'azure-hybrid-cloud': {
      title: 'Azure хибридна интеграция',
      eyebrow: 'Hybrid Cloud',
      lead: 'Разширяване на on-prem VMware или Proxmox към Azure за scalability, disaster recovery и secure hybrid operations.',
      subline: 'Hybrid работи, когато connectivity, identity, monitoring и recovery са проектирани като една система.',
      icon: 'infrastructure',
      buyer: ['Екипи, които не могат да преместят всичко в cloud наведнъж', 'Организации с нужда от DR или burst capacity в Azure', 'IT лидери, управляващи cloud и on-prem platforms'],
      deliver: ['Hybrid connectivity и identity design', 'Azure extension за selected workloads и DR scenarios', 'Unified monitoring и backup alignment', 'Operational model за cloud/on-prem ownership'],
      standards: ['Azure', 'VPN / ExpressRoute', 'Hybrid identity', 'Azure Monitor', 'DR planning'],
      caseTitle: 'Анонимизиран резултат',
      caseBody: 'Hybrid environment намали operational ambiguity чрез дефиниране какво остава on-prem, какво се разширява към Azure и как се monitor/recover-ват двете страни.',
      caseMetrics: ['hybrid DR', 'secure connectivity', 'unified monitoring']
    },
    'web-b2b-b2c': {
      title: 'Уеб B2B и B2C решения',
      eyebrow: 'Business Platforms',
      lead: 'Custom web platforms, интегрирани с ERP и бизнес системи според точните operational processes.',
      subline: 'Полезният софтуер отразява реалния процес — не обратното.',
      icon: 'web',
      buyer: ['Бизнеси с ordering или workflow complexity', 'Екипи с нужда от ERP-integrated customer/partner portals', 'Operations лидери, заменящи manual data transfer'],
      deliver: ['Process mapping и platform scope', 'ERP/API integration architecture', 'Secure modular web application delivery', 'Operational handover и support model'],
      standards: ['React / web apps', 'ERP integration', 'APIs', 'Security boundaries', 'Operational handover'],
      caseTitle: 'Анонимизиран резултат',
      caseBody: 'Workflow-heavy business намали manual coordination чрез integrated web platform с по-ясен ownership.',
      caseMetrics: ['ERP integration', 'less manual work', 'clear ownership']
    },
    'easy-order-platform': {
      title: 'Easy Order платформа',
      eyebrow: 'Order Management',
      lead: 'Интегрирана order-process платформа, свързваща клиенти, производители, складове и дистрибутори.',
      subline: 'Order workflows стават по-бързи, когато data transfer е автоматичен и видим за правилните участници.',
      icon: 'tools',
      buyer: ['Организации, координиращи orders между много страни', 'Екипи, заменящи spreadsheet/email order workflows', 'Бизнеси с нужда от status visibility и по-малко manual handoffs'],
      deliver: ['Order-flow mapping и role model', 'Customer, manufacturer, warehouse и distributor data paths', 'Automation rules и integration points', 'Support, reporting и operational handover'],
      standards: ['Order workflows', 'Data automation', 'Role-based access', 'ERP integration', 'Reporting'],
      caseTitle: 'Анонимизиран резултат',
      caseBody: 'Multi-party order process стана по-лесен за tracking и operation след замяна на manual handoffs с integrated workflow platform.',
      caseMetrics: ['automated flow', 'role visibility', 'fewer handoffs']
    },
    'gxp-clinical-research-it': {
      title: 'GxP и Clinical Research IT',
      eyebrow: 'Life Sciences IT',
      lead: 'Validated, audit-ready ИТ среди за CRO, clinical research и регулирани life-sciences екипи.',
      subline: 'Практична CSV и GAMP 5 aligned доставка за системи с нужда от evidence, traceability и controlled change.',
      icon: 'security',
      buyer: ['CRO и clinical research екипи с regulated workflows', 'Life-sciences организации, подготвящи audits или inspections', 'IT лидери с нужда от validation evidence без тежък consulting overhead'],
      deliver: ['GxP-relevant system inventory, ownership и risk classification', 'CSV / GAMP 5 aligned implementation и change-control evidence', 'Identity, backup, audit trail и access-review operating model', 'Vendor governance, SOP alignment и recovery evidence за regulated systems'],
      standards: ['GxP-aware IT', 'CSV', 'GAMP 5 aligned', 'Audit trails', 'Controlled change'],
      caseTitle: 'Анонимизиран резултат',
      caseBody: 'Regulated research екип подобри audit readiness чрез mapping на system ownership, access evidence, backup proof и change-control records в един operating model.',
      caseMetrics: ['audit evidence', 'controlled change', 'clear ownership']
    }
  }
}

export const solutionSlugs = ['microsoft-azure', 'microsoft-365', 'vmware-proxmox-virtualization', 'azure-hybrid-cloud', 'zero-trust-security', 'entra-id-sso', 'backup-dr-veeam', 'cloud-migration', 'web-b2b-b2c', 'easy-order-platform', 'gxp-clinical-research-it']
